[package]
name = "kclvm-error"
version = "0.9.0-alpha.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span = "0.1.2" 
compiler_base_session = "0.1.3"
compiler_base_error = "0.1.6"
compiler_base_macros = "0.1.1"
kclvm-span = {path = "../span"}
kclvm-runtime = {path = "../runtime"}
kclvm-utils = {path = "../utils"}

anyhow = "1.0"
tracing = "0.1"
atty = "0.2"
annotate-snippets = { version = "0.9.2", default-features = false, features = ["color"] }
termize = "0.1.1"
indexmap = "1.0"
serde_json = "1.0"
