[package]
name = "kclvm-version"
version = "0.9.0-alpha.2"
edition = "2021"

[build-dependencies]
vergen = { version = "8.1.3", features = ["git", "gitcl", "rustc"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
